name: Deploy Discord Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci  # Use npm ci for cleaner installs
        
    - name: Verify installation
      run: |
        echo "Checking installed packages:"
        npm list discord.js dotenv
        echo "Dependencies verified!"
        
    - name: Run bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        timeout 300 node index.js || echo "Bot stopped after 5 minutes"
